#!/usr/bin/env python3
"""Validate docs/air/mapping.yaml against the repo and render docs/framework-mapping.md.

    python3 scripts/check_air_mapping.py          # validate and render
    python3 scripts/check_air_mapping.py --check  # validate, and fail if the rendered doc is stale

Checks: every catalogue item has exactly one mapping entry and there are no extras, every knob and
lint id exists in the code, statuses come from the fixed vocabulary, and each entry says why.
"""
import re, sys, collections, pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATUSES = ["implemented", "declared", "partial", "gap", "out_of_scope"]

cat = yaml.safe_load((ROOT / "docs/air/catalogue.yaml").read_text())
mp = yaml.safe_load((ROOT / "docs/air/mapping.yaml").read_text())

registry = (ROOT / "crates/sandboxpolicy-core/src/registry.rs").read_text()
lint_src = (ROOT / "crates/sandboxpolicy-core/src/lint.rs").read_text()
knobs = set(re.findall(r'"(K\d\.\d)"', registry))
lints = set(re.findall(r"\| (L\d{3}) \|", lint_src))

errors = []
for kind, key in (("risks", "risks"), ("mitigations", "mitigations")):
    want = {i["ref"] for i in cat[key]}
    have = set(mp[key])
    for r in sorted(want - have):
        errors.append(f"{kind}: {r} has no mapping entry")
    for r in sorted(have - want):
        errors.append(f"{kind}: {r} is not in the catalogue")
    for ref, e in mp[key].items():
        if e.get("status") not in STATUSES:
            errors.append(f"{ref}: bad status {e.get('status')!r}")
        if not e.get("note"):
            errors.append(f"{ref}: missing note")
        if e.get("status") in ("partial", "gap") and not (e.get("gap") or e.get("note")):
            errors.append(f"{ref}: {e.get('status')} needs a gap")
        if e.get("status") == "partial" and not e.get("gap") and not e.get("where"):
            errors.append(f"{ref}: partial needs a gap or a where")
        if e.get("status") == "out_of_scope" and (e.get("knobs") or e.get("lint")):
            errors.append(f"{ref}: out_of_scope but lists knobs or lint")
        if e.get("status") in ("implemented", "partial", "declared") and not (
            e.get("knobs") or e.get("lint") or e.get("other")
        ):
            errors.append(f"{ref}: {e['status']} but names nothing in the repo")
        for k in e.get("knobs", []):
            if k not in knobs:
                errors.append(f"{ref}: unknown knob {k}")
        for l in e.get("lint", []):
            if l not in lints:
                errors.append(f"{ref}: unknown lint rule {l}")

if errors:
    print("\n".join(errors))
    sys.exit(1)

rid = {i["ref"]: i for i in cat["risks"]}
mid = {i["ref"]: i for i in cat["mitigations"]}
mit_for = collections.defaultdict(list)
for m in cat["mitigations"]:
    for r in m["mitigates"]:
        mit_for[r].append(m["id"])


def cell_refs(e):
    parts = []
    if e.get("knobs"):
        parts.append(", ".join(e["knobs"]))
    if e.get("lint"):
        parts.append(", ".join(e["lint"]))
    if e.get("other"):
        parts.append(", ".join(e["other"]))
    return "<br>".join(parts) if parts else "none"


def esc(s):
    return " ".join(str(s).split()).replace("|", "/")


def table(items, entries, extra=None):
    out = ["| ID | Title | Status | In this repo | Note | Gap | Enforced elsewhere |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for it in items:
        e = entries[it["ref"]]
        out.append(
            "| {} | {} | {} | {} | {} | {} | {} |".format(
                it["id"], esc(it["title"]), e["status"], cell_refs(e), esc(e["note"]),
                esc(e.get("gap", "")), esc(e.get("where", "")),
            )
        )
    return "\n".join(out)


def counts(key):
    c = collections.Counter(e["status"] for e in mp[key].values())
    return " | ".join(str(c.get(s, 0)) for s in STATUSES)


src = cat["source"]
gaps = []
for key, pool in (("risks", rid), ("mitigations", mid)):
    for ref, e in mp[key].items():
        if e.get("gap") or e["status"] == "gap":
            gaps.append((pool[ref]["id"], pool[ref]["title"], e.get("gap") or e["note"]))

doc = f"""# Mapping to the FINOS AI Governance Framework

Generated by `scripts/check_air_mapping.py` from `docs/air/catalogue.yaml` and `docs/air/mapping.yaml`.
Edit the YAML, not this file.

Every risk and every mitigation in the framework has exactly one entry, including the ones this
project does not address. The script fails if an item is missing, if an entry names a knob or lint
rule that does not exist in the code, or if the catalogue changes without the mapping.

## Source

- Framework: {src['repo']} at commit `{src['commit'][:12]}` ({src['commit_date']}), {src['licence']}. {src['note']}
- This is one reviewer's reading. Have someone who owns the framework at your organisation check it before it is published.

## How to read the statuses

| Status | Meaning |
| --- | --- |
| implemented | This repo validates or computes it, with tests in this repo. |
| declared | This repo carries the setting in the signed bundle. Enforcement is in mediatore, mediatore-guest or the gateway. |
| partial | Some of the above, and the gap column says what is missing. |
| gap | In scope for a sandbox policy layer, and nothing exists yet. |
| out_of_scope | Not a sandbox policy concern, such as model quality, bias or training data. |

Two limits apply to everything below. Nothing in this repo has run on a cluster yet. And "enforced
elsewhere" names where enforcement belongs, it does not claim those components do it today.

## Summary

| | {' | '.join(STATUSES)} |
| --- | --- | --- | --- | --- | --- |
| Risks ({len(cat['risks'])}) | {counts('risks')} |
| Mitigations ({len(cat['mitigations'])}) | {counts('mitigations')} |

## Risks

{table(cat['risks'], mp['risks'])}

### Which framework mitigations address each risk

The framework declares this relation. It is listed so a risk marked implemented or partial can be
checked against the controls the framework expects for it.

| Risk | Framework mitigations |
| --- | --- |
""" + "\n".join(
    f"| {r['id']} | {', '.join(mit_for[r['ref']]) or 'none declared'} |" for r in cat["risks"]
) + f"""

## Mitigations

{table(cat['mitigations'], mp['mitigations'])}

## Open gaps

""" + "\n".join(f"- **{i}** {esc(t)}: {esc(g)}" for i, t, g in gaps) + "\n"

out = ROOT / "docs/framework-mapping.md"
if "--check" in sys.argv:
    if not out.exists() or out.read_text() != doc:
        print("docs/framework-mapping.md is stale, run scripts/check_air_mapping.py")
        sys.exit(1)
    print("ok")
else:
    out.write_text(doc)
    print(f"wrote {out.relative_to(ROOT)}: {len(cat['risks'])} risks, {len(cat['mitigations'])} mitigations")
